# Generated by Django 4.1 on 2022-08-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moist_1", models.IntegerField(default=0)),
                ("moist_2", models.IntegerField(default=0)),
                ("temp", models.IntegerField(default=0)),
                ("rain", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
